# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master
